workflows:
  my-workflow:
    name: My iOS Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
    artifacts:
      - build/**/outputs/**/*.ipa  # Define the path to your IPA artifact
    publishing:
      email:
        recipients:
          - yassersabsibo@gmail.com
      scripts:
        - echo 'Post-publish script'